# Generated by Django 5.0.6 on 2024-08-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0003_category_quiz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='participants',
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='category/default.png', upload_to='category/'),
        ),
    ]
