# Generated by Django 5.0.6 on 2024-08-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_remove_quiz_participants_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_name', models.TextField()),
                ('reward_value', models.IntegerField()),
                ('reward_points_required', models.IntegerField()),
            ],
        ),
    ]
