# Generated by Django 5.0.6 on 2024-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='reward_image',
            field=models.ImageField(default='reward/default.png', upload_to='reward/'),
        ),
    ]
