# Generated by Django 5.0.6 on 2024-10-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_reward_reward_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='default/category/default.png', upload_to='category/'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='reward_image',
            field=models.ImageField(default='default/reward/default.png', upload_to='reward/'),
        ),
    ]
