# Generated by Django 5.0.6 on 2024-11-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0007_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
