# Generated by Django 5.0.6 on 2024-12-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0008_remove_quiz_category_remove_quiz_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='uuid',
        ),
    ]
